### ISSUE TITLE
Implement the Truebit verification game

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/incentive-layer#15]
Use the binary search implementation which can be found in the `scrypt-interactive` repo to play the verification game.

**Comment by hswick** [comment]
Test synchronous blocking solidity call

**Comment by mrsmkl** [comment]
This is my implementation of the verification game: https://github.com/TrueBitFoundation/webasm-solidity/blob/master/interactive2.sol

**Comment by hswick** [comment]
This should now be develop interface for dispute resolution layer

**Comment by hswick** [comment]
This is being moved to dispute resolution layer
