### ISSUE TITLE
Use TypeScript for tests

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/incentive-layer#19]
This will give us stronger type-safety than using vanilla js.

**Comment by hswick** [comment]
This is also an option https://flow.org/

**Comment by adklempner** [comment]
The 0x project is leading the way when it comes to TypeScript and web3.
They've created [web3 typings](https://github.com/0xProject/0x-monorepo/tree/development/packages/web3-typescript-typings) and an extensive set of utilities, demonstrated in their [tests](https://github.com/0xProject/0x-monorepo/blob/development/packages/contracts/test/ether_token.ts)

I just started dipping my toes in TypeScript and so far it's a more enjoyable dev experience than vanilla js.

**Comment by hswick** [comment]
@adklempner said he would take on this issue.

**Comment by adklempner** [comment]
After digging through 0x’s [contracts](https://github.com/0xProject/0x-monorepo/tree/development/packages/contracts) package to understand their testing setup, I learned that their toolset is more extensive than I thought. There’s a lot of stuff that’s exclusive to the 0x project, along with more general contract testing tools that could be very helpful. Cleanly picking apart what’s needed for running TypeScript tests in this project isn’t entirely clear to me, so what I plan to do is strip down their repo of everything that’s exclusive to 0x and create a boilerplate project for testing Solidity contracts with TypeScript that implements their toolset. I mentioned this in their rocket chat and their senior engineer said they’re happy to help.

This will familiarize me with 0x’s development setup and I’ll be able to give you insight on whether or not it’s worth using their tools for this project (or any other Solidity project 😁 )

The boilerplate is obviously out of scope for this issue, so if anyone thinks they can get this done faster, feel free to take this on.
