### ISSUE TITLE
Distribute the reward, deposits, and jackpot at the end of a task's lifecycle

### ISSUE THREAD

**Issue by sinahab** [TrueBitFoundation/incentive-layer#30]
Using the white paper as reference, determine how rewards / deposits / jackpot are to be allocated at the end of a task's lifecycle.

To start – this is a summary of all funds that the smart contract will have available per task:
* “reward”: submitted by taskGiver.
* “deposit”: submitted by the chosen solver.
* n x “deposit”: submitted by n verifiers challenging solutionA.
* m x “deposit”: submitted by m verifiers challenging solutionB.
* k x “deposit”: submmited by the k verifiers challenging solutionA AND solutionB
* “Jackpot”: a task-book wide jackpot.

**Comment by hswick** [comment]
Started this with latest PR that makes unbondDeposit public.

This needs to be implemented as pull not push so contract does not get stuck.
