### ISSUE TITLE
Exponential Drop Off for Verifier Reward

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/incentive-layer#48]
payout for verifiers follows exponential drop off function

This is meant to disincentivize people from submitting multiple challenges to same task to get larger share of jackpot.

Use challenger's index position in challengers array. Larger index means less reward because that means the challenge came in later.

**Comment by hswick** [comment]
Not sure this makes sense in Truebit Classic. The effect of the exponential drop off is negated by incentives around jackpot. If expected return from jackpot is high enough, rational verifiers should try to verify as many tasks as possible

**Comment by sbaks0820** [comment]
Latest merged incentive layer from my fork adds this functionality to the incentive layer. Issue can be closed.
