### ISSUE TITLE
State channels

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/incentive-layer#5]
@zmitton mentioned the need for state channels because the transaction fees will be high. Came upon this blog post from the Grid+ team https://blog.gridplus.io/a-simple-ethereum-payment-channel-implementation-2d320d1fad93, we could use this as for when users are submitting deposits. Would need to modify it for the TaskBook features

**Comment by zmitton** [comment]
Nice, I really like the one by Matthew Di Ferrante. Its great and gets to the heart of the idea in the least possible steps @hswick

**Comment by hswick** [comment]
Totally. Was thinking we would have to integrate with Raiden. Glad a solution like this exists.

**Comment by hswick** [comment]
Based on discussions with phabc on Slack about using state channels.

The relevant problem for incentive layer is the nothing at stake problem.

Ex: TaskGiver posts a task with relevant data on Twitter. Solver solves it, verifier verifies it. All good. Right? No, because lets say a Solver has $100 worth of a deposit, and then decides to solve 20 tasks that are worth $10. The solver has nothing at stake for 10 tasks! Who is going to stop them? Nobody... 

Summary - In order to use an offchain mechanism like state channels the nothing at stake problem has to be solved

**Comment by teutsch** [comment]
You might be able to run the steps of the verification game through a state channel.

**Comment by hswick** [comment]
@teutsch mentioned that here https://github.com/TrueBitFoundation/dispute-resolution-layer/issues/3

**Comment by sinahab** [comment]
There is a new state channel for each verification game – i.e. Solver & Verifier have to deposit their collateral into a new multisig. Doesn't this prevent a nothing-at-stake problem?

**Comment by hswick** [comment]
@sinahab yes, if we are more specific. The deposit must get bonded first, which means:
TaskGiver has to post new task onchain, solver has to register for task onchain, and verifier has to commit to solution onchain.

My comments above were in response to @PhABC in the slack about having deposits prebonded and then doing the above offchain.

Unfortunately, after the above steps, I don't see very much benefit in having a state channel setup for this part of the protocol. There are only about 3 more states of the incentive layer FSM left. And they are all pretty much timeout dependent, so speed isn't even necessary.

The throughput is already limited by the deposit bonding steps :man_shrugging:

**Comment by hswick** [comment]
We can reissue this after initial release
