### ISSUE TITLE
Duplicate declaration error 

### ISSUE THREAD

**Issue by thogiti** [TrueBitFoundation/incentive-layer#76]
Duplicate declaration error <code> ExchangeRateOracle oracle; </code> in <code>IncentiveLayer.sol </code>.

/incentive-layer/contracts/IncentiveLayer.sol:106:5: DeclarationError: Identifier already declared.

/incentive-layer/contracts/IncentiveLayer.sol:93:5: The previous declaration is here:

To fix this, you need to comment the second declaration on line 106,

**Comment by hswick** [comment]
Thanks for pointing this out!

**Comment by thogiti** [comment]
Thx @hswick
