### ISSUE TITLE
Duplicate constructor error in incentivelayer.sol

### ISSUE THREAD

**Issue by thogiti** [TrueBitFoundation/incentive-layer#77]
The constructor was defined twice in <code>IncentiveLayer.sol</code>.

<code>
/incentive-layer/contracts/IncentiveLayer.sol:108:5: DeclarationError: More than one constructor defined. 
constructor (address _TRU, address _exchangeRateOracle)
    ^ (Relevant source part starts here and spans across multiple lines).
/incentive-layer/contracts/IncentiveLayer.sol:96:5: Another declaration is here:
    constructor (address _TRU, address _exchangeRateOracle, address _disputeResolutionLayer)
    ^ (Relevant source part starts here and spans across multiple lines).
</code>

To fix this, comment the the second declaration on line 108.

**Comment by thogiti** [comment]
Another duplicate function declaration  on line 314.

<code>
/incentive-layer/contracts/IncentiveLayer.sol:317:5: DeclarationError: Function with same name and arguments defined twice.
    function prematureReveal(uint taskID, uint originalRandomBits) public returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
/incentive-layer/contracts/IncentiveLayer.sol:341:5: Other declaration is here:
    function prematureReveal(uint taskID, uint originalRandomBits) public returns (bool) {
    ^ (Relevant source part starts here and spans across multiple lines).

</code>

**Comment by hswick** [comment]
Thanks!
